# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple-auth}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Sokolov"]
  s.date = %q{2010-12-08}
  s.description = %q{Static authentication && authorization in rails}
  s.email = %q{gzigzigzeo@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "lib/simple-auth.rb",
     "lib/simple-auth/railtie.rb",
     "lib/simple-auth/session.rb",
     "spec/simple-auth/simple-auth_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/gzigzigzeo/simple-auth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Static authentication && authorization in rails. Supports roles and static passwords.}
  s.test_files = [
    "spec/simple-auth/simple-auth_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["> 3"])
      s.add_runtime_dependency(%q<activesupport>, ["> 3"])
      s.add_runtime_dependency(%q<bcrypt-ruby>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, ["> 3"])
      s.add_dependency(%q<activesupport>, ["> 3"])
      s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, ["> 3"])
    s.add_dependency(%q<activesupport>, ["> 3"])
    s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
  end
end

